// src/web/src/components/shared/StatusBadge.tsx
import type { InvoiceStatus, QuotationStatus } from '@/types'
import { Badge } from '@/components/ui/badge'
import { cn } from '@/lib/utils'

const invoiceLabels: Record<InvoiceStatus, string> = {
  Draft: 'Draft',
  Awaiting: 'Awaiting',
  Paid: 'Paid',
  Overdue: 'Overdue',
}

const invoiceStyles: Record<InvoiceStatus, string> = {
  Draft: 'bg-gray-100 text-gray-600',
  Awaiting: 'bg-amber-100 text-amber-700',
  Paid: 'bg-green-100 text-green-700',
  Overdue: 'bg-red-100 text-red-700',
}

const quotationLabels: Record<QuotationStatus, string> = {
  Draft: 'Draft',
  Sent: 'Sent',
  Accepted: 'Accepted',
  Declined: 'Declined',
  Expired: 'Expired',
  ConvertedToInvoice: 'Converted to Invoice',
}

const quotationStyles: Record<QuotationStatus, string> = {
  Draft: 'bg-gray-100 text-gray-600',
  Sent: 'bg-amber-100 text-amber-800',
  Accepted: 'bg-blue-100 text-blue-700',
  Declined: 'bg-red-100 text-red-700',
  Expired: 'bg-gray-100 text-gray-500',
  ConvertedToInvoice: 'bg-green-100 text-green-700',
}

export function InvoiceStatusBadge({ status }: { status: InvoiceStatus }) {
  return (
    <Badge variant="secondary" className={cn('font-normal', invoiceStyles[status])}>
      {invoiceLabels[status]}
    </Badge>
  )
}

export function QuotationStatusBadge({ status }: { status: QuotationStatus }) {
  return (
    <Badge variant="secondary" className={cn('font-normal', quotationStyles[status])}>
      {quotationLabels[status]}
    </Badge>
  )
}

export function DocStatusBadge({ status }: { status: 'Draft' | 'Submitted' | 'Posted' | 'Cancelled' }) {
  const map = {
    Draft: { label: 'Draft', className: 'bg-gray-100 text-gray-600' },
    Submitted: { label: 'Submitted', className: 'bg-blue-100 text-blue-700' },
    Posted: { label: 'Posted', className: 'bg-green-100 text-green-700' },
    Cancelled: { label: 'Cancelled', className: 'bg-gray-100 text-gray-500' },
  }
  const { label, className } = map[status]
  return (
    <Badge variant="secondary" className={cn('font-normal', className)}>
      {label}
    </Badge>
  )
}

export function isQuotationTerminal(status: QuotationStatus): boolean {
  return status === 'Declined' || status === 'Expired' || status === 'ConvertedToInvoice'
}

export function canConvertQuotation(status: QuotationStatus): boolean {
  return status === 'Sent' || status === 'Accepted'
}

// src/ng/src/app/shared/components/status-badge/status-badge.component.ts
import { Component, Input } from '@angular/core'

const LABEL_MAP: Record<string, string> = {
  Draft:              'Draft',
  Awaiting:           'Awaiting',
  Paid:               'Paid',
  Overdue:            'Overdue',
  Sent:               'Sent',
  Accepted:           'Accepted',
  Declined:           'Declined',
  Expired:            'Expired',
  ConvertedToInvoice: 'Converted',
  Submitted:          'Submitted',
  Cancelled:          'Cancelled',
  Posted:             'Posted',
  not_invoiced:       'Not Invoiced',
  partially_invoiced: 'Partial',
  invoiced:           'Invoiced',
}

// Tailwind classes for each colour variant
const CLASS_MAP: Record<string, string> = {
  Draft:              'border-slate-200  bg-slate-100  text-slate-600',
  Awaiting:           'border-blue-200   bg-blue-50    text-blue-700',
  Paid:               'border-green-200  bg-green-50   text-green-700',
  Overdue:            'border-red-200    bg-red-50     text-red-700',
  Sent:               'border-blue-200   bg-blue-50    text-blue-700',
  Accepted:           'border-green-200  bg-green-50   text-green-700',
  Declined:           'border-red-200    bg-red-50     text-red-700',
  Expired:            'border-orange-200 bg-orange-50  text-orange-700',
  ConvertedToInvoice: 'border-purple-200 bg-purple-50  text-purple-700',
  Submitted:          'border-blue-200   bg-blue-50    text-blue-700',
  Cancelled:          'border-red-200    bg-red-50     text-red-700',
  Posted:             'border-green-200  bg-green-50   text-green-700',
  not_invoiced:       'border-orange-200 bg-orange-50  text-orange-700',
  partially_invoiced: 'border-blue-200   bg-blue-50    text-blue-700',
  invoiced:           'border-green-200  bg-green-50   text-green-700',
}

const BASE = 'inline-flex items-center rounded-full border px-2.5 py-0.5 text-xs font-semibold whitespace-nowrap'

@Component({
  selector: 'app-status-badge',
  standalone: true,
  template: `<span [class]="classes">{{ label }}</span>`,
})
export class StatusBadgeComponent {
  @Input() status = ''

  get label(): string { return LABEL_MAP[this.status] ?? this.status }
  get classes(): string {
    return `${BASE} ${CLASS_MAP[this.status] ?? 'border-slate-200 bg-slate-100 text-slate-600'}`
  }
}
